name: Schema validation

on:
  - push

jobs:
  schema:
    name: Schema validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn run prevalidate
      - run: yarn run validate
